version: "3.9"
services:
  webserver:
    container_name: Medical-PHP-webServer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
    depends_on:
      - postgres-db
    networks:
      medical_network:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-db:
    image: postgres:15.3-alpine3.17
    container_name: Medical-postgres-15
    command:
      - "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: medical-2024
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgresdb-data:/var/lib/postgresql/data
      - ./postgres:/dump
    ports:
      - "5433:5432"
    networks:
      medical_network:

volumes:
  postgresdb-data:

networks:
  medical_network:
    driver: bridge
    name: medical_network
    ipam:
      driver: default
      config:
        - subnet: 172.36.0.0/25
