nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["*"]
    allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin:
        ["http://localhost:5173", "https://your-frontend-domain.com"]
      allow_methods: ["GET", "POST", "PUT", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
